#!/bin/bash

set -eu

echo " -> Installing packages"
sudo apt install -qq \
  aria2 \
  curl \
  fzf \
  git \
  htop \
  jq \
  less \
  ripgrep \
  shellcheck \
  tree \
  unrar \
  unzip \
  vim \
  wget \
  youtube-dl \
  zip \
  
VIM_PLUG="${HOME}/.vim/autoload/plug.vim"
if [ ! -f ${VIM_PLUG} ]; then
  echo " -> Installing vim plugins"
  curl -fLo ${VIM_PLUG} --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  
  mkdir -p "${HOME}/.vim/plugged"
  pushd "${HOME}/.vim/plugged"
  git clone "https://github.com/airblade/vim-gitgutter.git"
  git clone "https://github.com/itchyny/lightline.vim.git"
  popd
fi

echo ""
echo " -> Done!"
