#!/bin/bash

set -eu

echo " -> Installing packages"
sudo apt-get install -qq \
  aria2 \
  curl \
  git \
  htop \
  less \
  make \
  shellcheck \
  tree \
  unrar \
  unzip \
  vim \
  wget \
  youtube-dl \
  zip \
  --no-install-recommends \
  
VIM_PLUG="${HOME}/.vim/autoload/plug.vim"
if [ ! -f ${VIM_PLUG} ]; then
  echo " -> Installing vim plugins"
  curl -fLo ${VIM_PLUG} --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  mkdir -p "${HOME}/.vim/plugged"
fi

TERRAFORM_VERSION="0.13.2"
echo " -> Installing Terraform"
curl -fLO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
sudo mv terraform /usr/local/bin/terraform
sudo chmod 755 /usr/local/bin/terraform
rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

PACKER_VERSION="1.6.2"
echo " -> Installing Packer"
curl -fLO https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
unzip packer_${PACKER_VERSION}_linux_amd64.zip
sudo mv packer /usr/local/bin/packer
sudo chmod 755 /usr/local/bin/packer
rm -f packer_${PACKER_VERSION}_linux_amd64.zip

YQ_VERSION="3.3.4"
echo " -> Install yq"
curl -fLO https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64
sudo mv yq_linux_amd64 /usr/local/bin/yq
sudo chmod 755 /usr/local/bin/yq

JQ_VERSION="1.6"
echo " -> Install jq"
curl -fLO https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64
sudo mv jq-linux64 /usr/local/bin/jq
sudo chmod 755 /usr/local/bin/jq

echo " -> Install fzf"
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --key-bindings --no-completion --no-update-rc --no-zsh --no-fish

echo ""
echo " -> Done!"
