#!/usr/bin/env bash

function running() {
    echo -e " -> "$1""
}

# Close any open System Preferences panes, to prevent them from overriding settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'


# General UI/UX

running "Disable transparency"
defaults write com.apple.universalaccess reduceTransparency -bool true

running "Show scrollbars base on mouse/trackpad"
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"

running "Expanding the save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

running "Turn off keyboard illumination when computer is not used for 5 minutes"
defaults write com.apple.BezelServices kDimTime -int 300


# Dock, Mission Control

running "Change minimize/maximize window effect"
defaults write com.apple.dock mineffect -string "scale"

running "Automatically hide the Dock"
defaults write com.apple.dock autohide -bool true

running "Dock auto-hide delay"
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide-time-modifier -float 0.5

running "Don’t show recent applications in Dock"
defaults write com.apple.dock show-recents -bool false

running "Setting the icon size of Dock items to 24 pixels"
defaults write com.apple.dock tilesize -int 24

running "Speed up Mission Control animations"
defaults write com.apple.dock expose-animation-duration -float 0.1

running "Don’t automatically rearrange Spaces based on most recent use"
defaults write com.apple.dock mru-spaces -bool false


# Input

running "Setting trackpad & mouse speed to a reasonable number"
defaults write -g com.apple.trackpad.scaling 2
defaults write -g com.apple.mouse.scaling 2.5

running "Disable natural scrolling"
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

running "Set key repeat rate"
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15


# Screen

running "Require password immediately after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0


# Finder

running "Finder: show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

running "Keep folders on top when sorting by name"
defaults write com.apple.finder _FXSortFoldersFirst -bool true

running "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

running "Avoid creating .DS_Store files on network or USB volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true


# Safari

running "Show the full URL in the address bar (note: this still hides the scheme)"
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

running "Prevent Safari from opening ‘safe’ files automatically after downloading"
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

running "Hide Safari’s bookmarks bar by default"
defaults write com.apple.Safari ShowFavoritesBar -bool false

running "Enable the Develop menu and the Web Inspector in Safari"
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

running "Disable AutoFill"
defaults write com.apple.Safari AutoFillFromAddressBook -bool false
defaults write com.apple.Safari AutoFillPasswords -bool false
defaults write com.apple.Safari AutoFillCreditCardData -bool false
defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false

running "Update extensions automatically"
defaults write com.apple.Safari InstallExtensionUpdatesAutomatically -bool true


# Google Chrome

running "Disabling the annoying backswipe in Chrome"
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false


# Mail.app

running "Disable send and reply animations in Mail.app"
defaults write com.apple.mail DisableReplyAnimations -bool true
defaults write com.apple.mail DisableSendAnimations -bool true

running "Copy email addresses as foo@bar.com instead of Foo Bar <foo@bar.com> in Mail.app"
defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

running "Disable inline attachments (just show the icons)"
defaults write com.apple.mail DisableInlineAttachmentViewing -bool true


# TextEdit

running "Use plain text mode for new TextEdit documents"
defaults write com.apple.TextEdit RichText -int 0

running "Open and save files as UTF-8 in TextEdit"
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4


for app in "Dock" "Finder" "Google Chrome" "Mail" "Safari" "SystemUIServer"; do
  killall "$app" > /dev/null 2>&1
done

echo "Done!"
