" vim plug
call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
call plug#end()

syntax on
set termguicolors
set background=dark
let g:monotone_emphasize_comments = 1
colorscheme monotone

set encoding=utf-8
set autoread
set autoindent
set backspace=indent,eol,start
set incsearch
set hlsearch
set ignorecase
set smartcase
set mouse=a

set laststatus=2
set noerrorbells
set number
set ruler
set showcmd
set nobackup
set fileformats=unix,dos,mac
set nocursorcolumn
set nocursorline

set tabstop=2
set shiftwidth=2
set expandtab

if has('persistent_undo')
  set undofile
  set undodir=~/.cache/vim
endif
