" vim plug
call plug#begin('~/.vim/plugged')
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
call plug#end()

syntax on
set termguicolors

let g:monotone_color = [10, 50, 80]
let g:monotone_emphasize_comments = 1
colorscheme monotone

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smarttab

set number
set ruler

set backupcopy=yes

set ignorecase
set smartcase

set fileformat=unix

set mouse=a

" undodir
if !isdirectory($HOME."/.vim")
  call mkdir($HOME."/.vim", "", 0770)
endif
if !isdirectory($HOME."/.vim/undodir")
  call mkdir($HOME."/.vim/undodir", "", 0700)
endif
set undofile
set undodir=~/.vim/undodir

