" vim plug
call plug#begin('~/.vim/plugged')
Plug 'nikitavoloboev/vim-monokai-night'
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
call plug#end()

set termguicolors
syntax on
colorscheme monokai-night

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab

set number
set ruler

set backupcopy=yes

set ignorecase
set smartcase

set fileformat=unix

set mouse=a

" undodir
if !isdirectory($HOME."/.vim")
    call mkdir($HOME."/.vim", "", 0770)
endif
if !isdirectory($HOME."/.vim/undodir")
    call mkdir($HOME."/.vim/undodir", "", 0700)
endif
set undofile
set undodir=~/.vim/undodir

" lightline
set laststatus=2
set noshowmode

