#!/usr/bin/env bash

# Prompt
export PS1="\n\h \w \\$ \[$(tput sgr0)\]"


# History
export HISTSIZE=10000
export HISEFILESIZE=10000


# Golang
GOPATH=$HOME/go
export GOPATH

# Bash Completion
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"


# Aliases
alias ll="ls -lh"
alias la="ls -lha"
alias lt="ls -lrt"

alias gcc="gcc-9"
alias g++="g++-9"


# Custom Functions
function cheat() {
  curl cht.sh/"$1"
}


# Finalizing
export PATH

