[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "shfmt", args = ["-i", "4"] }

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[[language]]
name = "hcl"
language-servers = [ "terraform-ls" ]
language-id = "terraform"

[[language]]
name = "tfvars"
language-servers = [ "terraform-ls" ]
language-id = "terraform-vars"

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]
